before_install: sudo apt-get install libzmq3-dev
script: bundle exec rspec
language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - rbx-2
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#wires"